ep_per_batch: 4
load_encoder: ./checkpoints/mini/smkd.pth
max_epoch: 20
model: meta-baseline
model_args:
  encoder: vit-small
  encoder_args: {}
n_query: 15
n_shot: 1
n_way: 5
optimizer: adamw
optimizer_args:
  lr: 1.0e-05
  weight_decay: 0.0005
train_batches: 200
train_dataset: mini-imagenet
train_dataset_args:
  split: train
tval_dataset: mini-imagenet
tval_dataset_args:
  split: test
val_dataset: mini-imagenet
val_dataset_args:
  split: val
visualize_datasets: true
